### ISSUE TITLE
Inherited templates seem to be cached somehow

### ISSUE THREAD

**Issue by samjhayes** [gamernetwork/gn-django#89]
If you try and inherit from a core template in a frontend app (using the `HierarchyLoader`) the changes aren't reflected in the frontend  until the container is restarted, making development very difficult!

(For example if you create `templates/components/page_header.j2` in `demo_content` to extend from `core:templates/components/page_header.j2`)

**Comment by thomasjthomasj** [comment]
So I've looked into this a bit and I've diagnosed the problem. <a href="https://github.com/pallets/jinja/blob/master/jinja2/loaders.py#L181">This method</a> gives false positives and so the template is loaded from memory instead of the file. I'm not sure how best to fix this, but I've done a <a href="https://github.com/gamernetwork/gn-django/blob/thomas-template-cache-dontmerge/gn_django/template/loaders.py#L277">temporary fix</a> which I'd rather not merge by overriding the class/method and having it always return `False` in debug mode

**Comment by thomasjthomasj** [comment]
It look like at some point the `uptodate` closure gets set against the `Template` instance itself and this is called before the file is reloaded. On first load this is `None` but on second load this is set https://github.com/pallets/jinja/blob/fb7e12cce67b9849899f934e697f7e2a91d604c2/jinja2/environment.py#L960

**Comment by thomasjthomasj** [comment]
This is a non-issue that is already solved if you use the right template setting

```python
'environment': 'gn_django.template.backend.environment'
```
